import { env } from "cloudflare:workers";
type B={DB?:D1Database;PROFILE_IMAGES?:R2Bucket};
type P=Record<string,unknown>&{profileImage?:string;profileBackground?:string;_profileImageStored?:boolean;_profileBackgroundStored?:boolean};
function bindings(){const e=env as unknown as B;if(!e.DB)throw new Error("D1 binding DB is unavailable.");if(!e.PROFILE_IMAGES)throw new Error("R2 binding PROFILE_IMAGES is unavailable.");return {DB:e.DB,PROFILE_IMAGES:e.PROFILE_IMAGES}}
function valid(v:string|null){const id=String(v||"").trim();return /^[A-Za-z0-9_-]{1,100}$/.test(id)?id:""}
async function table(db:D1Database){await db.prepare("CREATE TABLE IF NOT EXISTS live_profiles (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_at TEXT NOT NULL)").run()}
function image(v:unknown){const s=typeof v==="string"?v:"";const m=s.match(/^data:(image\/(?:png|jpe?g|webp|gif));base64,([A-Za-z0-9+/=\s]+)$/i);if(!m)return null;const raw=atob(m[2].replace(/\s+/g,""));if(!raw.length||raw.length>2500000)throw new Error("Uploaded image is too large after compression.");const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return {bytes,mime:m[1].toLowerCase()==="image/jpg"?"image/jpeg":m[1].toLowerCase()}}
async function previous(db:D1Database,id:string){const row=await db.prepare("SELECT data FROM live_profiles WHERE id=?").bind(id).first<{data:string}>();if(!row?.data)return null;try{return JSON.parse(row.data) as P}catch{return null}}
export async function GET(request:Request){try{const {DB}=bindings(),url=new URL(request.url),id=valid(url.searchParams.get("id"));if(!id)return Response.json({error:"Invalid profile ID."},{status:400});await table(DB);const row=await DB.prepare("SELECT data,updated_at FROM live_profiles WHERE id=?").bind(id).first<{data:string;updated_at:string}>();if(!row)return Response.json({error:"Profile not found."},{status:404});const p=JSON.parse(row.data) as P,v=encodeURIComponent(row.updated_at||""),o=url.origin;if(p._profileImageStored)p.profileImage=o+"/api/profile-image?id="+encodeURIComponent(id)+"&kind=profile&v="+v;if(p._profileBackgroundStored)p.profileBackground=o+"/api/profile-image?id="+encodeURIComponent(id)+"&kind=background&v="+v;delete p._profileImageStored;delete p._profileBackgroundStored;return Response.json({profile:p,updatedAt:row.updated_at},{headers:{"Cache-Control":"no-store"}})}catch(e){return Response.json({error:e instanceof Error?e.message:"Live profile storage is unavailable."},{status:503})}}
export async function PUT(request:Request){try{const {DB,PROFILE_IMAGES}=bindings(),url=new URL(request.url),id=valid(url.searchParams.get("id"));if(!id)return Response.json({error:"Invalid profile ID."},{status:400});const input=await request.json() as {profile?:P;profileImage?:string;profileBackground?:string};if(!input.profile||typeof input.profile!=="object"||Array.isArray(input.profile))return Response.json({error:"Profile data is required."},{status:400});await table(DB);const prev=(await previous(DB,id))||{},stored=JSON.parse(JSON.stringify(input.profile)) as P,now=new Date().toISOString();const pi=image(input.profileImage)||image(stored.profileImage),bg=image(input.profileBackground)||image(stored.profileBackground);if(pi){await PROFILE_IMAGES.put("profiles/"+id+"/profile",pi.bytes,{httpMetadata:{contentType:pi.mime},customMetadata:{updatedAt:now}});stored.profileImage="";stored._profileImageStored=true}else if(prev._profileImageStored)stored._profileImageStored=true;if(bg){await PROFILE_IMAGES.put("profiles/"+id+"/background",bg.bytes,{httpMetadata:{contentType:bg.mime},customMetadata:{updatedAt:now}});stored.profileBackground="";stored._profileBackgroundStored=true}else if(prev._profileBackgroundStored)stored._profileBackgroundStored=true;delete stored._lessDenseUpdatedAt;await DB.prepare("INSERT INTO live_profiles(id,data,updated_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at").bind(id,JSON.stringify(stored),now).run();return Response.json({ok:true,id,updatedAt:now},{headers:{"Cache-Control":"no-store"}})}catch(e){return Response.json({error:e instanceof Error?e.message:"The profile could not be saved."},{status:503})}}
