CREATE TABLE IF NOT EXISTS contacts (
    id VARCHAR(100) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
    first_name VARCHAR(120) NOT NULL,
    last_name VARCHAR(120) NOT NULL,
    phone_number VARCHAR(80) NOT NULL DEFAULT '',
    mobile VARCHAR(80) NOT NULL,
    email VARCHAR(254) NOT NULL DEFAULT '',
    website VARCHAR(2048) NOT NULL DEFAULT '',
    company VARCHAR(255) NOT NULL DEFAULT '',
    job_title VARCHAR(255) NOT NULL DEFAULT '',
    fax VARCHAR(80) NOT NULL DEFAULT '',
    address VARCHAR(500) NOT NULL DEFAULT '',
    city VARCHAR(120) NOT NULL DEFAULT '',
    post_code VARCHAR(40) NOT NULL DEFAULT '',
    country VARCHAR(120) NOT NULL DEFAULT '',
    wechat_id VARCHAR(120) NOT NULL DEFAULT '',
    whatsapp_message TEXT NOT NULL,
    extra_phones JSON NOT NULL,
    extra_emails JSON NOT NULL,
    extra_websites JSON NOT NULL,
    extra_addresses JSON NOT NULL,
    profile_image_path VARCHAR(255) NULL,
    profile_background_path VARCHAR(255) NULL,
    profile_image_url VARCHAR(2048) NOT NULL DEFAULT '',
    profile_background_url VARCHAR(2048) NOT NULL DEFAULT '',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    INDEX contacts_name_idx (last_name, first_name),
    INDEX contacts_country_idx (country),
    INDEX contacts_company_idx (company),
    INDEX contacts_status_idx (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
